
from fpdf import FPDF
import os
import pandas as pd
from datetime import datetime
from data_loader import get_latest_data
from groundwater.pipeline.forecasting import ForecastingPipeline

class PDF(FPDF):
    def header(self):
        # Logo could go here
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'Groundwater Analysis Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

class ReportGenerator:
    def __init__(self):
        self.output_dir = "reports_generated"
        os.makedirs(self.output_dir, exist_ok=True)
        self.forecasting = ForecastingPipeline()

    def generate_report(self, station_id):
        # 1. Fetch Data
        latest = get_latest_data(station_id)
        if not latest:
            raise Exception("Station not found")
            
        # 2. Get Forecast (Default parameters)
        try:
            forecasts = self.forecasting.predict_future(station_id=station_id, years=3)
        except:
            forecasts = []

        # 3. Create PDF
        pdf = PDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_font('Arial', '', 12)

        # Title Section
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, f"Station Analysis: {station_id}", 0, 1)
        pdf.ln(5)

        # Current Status Table
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, "Current Status", 0, 1)
        pdf.set_font('Arial', '', 11)
        
        # Simple data rows
        self._add_row(pdf, "Location (Lat, Lon)", f"{latest.get('LAT')}, {latest.get('LON')}")
        self._add_row(pdf, "Water Level", f"{round(latest.get('Water_Level', 0), 2)} mbgl")
        self._add_row(pdf, "Zone Classification", f"{latest.get('zone', 'Unknown')}")
        self._add_row(pdf, "Date of Last Record", f"{latest.get('Date')}")
        
        pdf.ln(10)

        # Future Projection
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, "Future Projection (Next 3 Years)", 0, 1)
        
        # Table Header
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(40, 10, 'Date', 1)
        pdf.cell(40, 10, 'Predicted Level', 1)
        pdf.cell(40, 10, 'Zone Status', 1)
        pdf.ln()

        # Table Body (first 12 entries - 3 years of quarterly)
        pdf.set_font('Arial', '', 10)
        for row in forecasts[:12]: 
            pdf.cell(40, 10, str(row['Date']), 1)
            pdf.cell(40, 10, f"{row['Water_Level']} m", 1)
            pdf.cell(40, 10, str(row['Zone']), 1)
            pdf.ln()

        pdf.ln(10)
        pdf.set_font('Arial', 'I', 9)
        pdf.multi_cell(0, 10, "Disclaimer: These predictions are generated by an AI model based on historical trends. Actual values may vary due to environmental changes.")

        # Save
        filename = f"Report_{station_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath, 'F')
        
        return filepath

    def _add_row(self, pdf, label, value):
        pdf.cell(60, 8, label, 0)
        pdf.cell(0, 8, f": {value}", 0, 1)

